const CartActionTypes = {
    ADD_TO_CART: 'ADD_TO_CART', 
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    CART_SAVE_SHIPPING_ADDRESS: 'CART_SAVE_SHIPPING_ADDRESS',
    CART_SAVE_PAYMENT_METHOD: "CART_SAVE_PAYMENT_METHOD",
    PLACE_ORDER: "PLACE_ORDER"
}

export default CartActionTypes;